version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://143.198.76.123/api
      - CHOKIDAR_USEPOLLING=true
    restart: always
    ports:
      - "3000:3000"
#REACT_APP_BACKEND_URL=http://146.190.116.27/api