export const GET_NEWS_REQUEST = 'GET_NEWS_REQUEST';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_FAILURE = 'GET_NEWS_FAILURE';

export const GET_CRYPTO_NEWS_REQUEST = 'GET_CRYPTO_NEWS_REQUEST';
export const GET_CRYPTO_NEWS_SUCCESS = 'GET_CRYPTO_NEWS_SUCCESS';
export const GET_CRYPTO_NEWS_FAILURE = 'GET_CRYPTO_NEWS_FAILURE';

export const GET_STOCKS_NEWS_REQUEST = 'GET_STOCKS_NEWS_REQUEST';
export const GET_STOCKS_NEWS_SUCCESS = 'GET_STOCKS_NEWS_SUCCESS';
export const GET_STOCKS_NEWS_FAILURE = 'GET_STOCKS_NEWS_FAILURE';

export const SEARCH_NEWS_REQUEST = 'SEARCH_NEWS_REQUEST';
export const SEARCH_NEWS_SUCCESS = 'SEARCH_NEWS_SUCCESS';
export const SEARCH_NEWS_FAILURE = 'SEARCH_NEWS_FAILURE';