version: '3'

services:
  mongoDb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - db-volume:/data/db
    ports:
      - "27017:27017"
      
volumes:
  db-volume:
